"""add replay

Revision ID: 7d3c8748aaa2
Revises: 7c5d5a2f3544
Create Date: 2025-01-10 15:08:15.552789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d3c8748aaa2"
down_revision: Union[str, None] = "7c5d5a2f3544"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "replay",
        sa.Column("counter", sa.Integer(), nullable=False),
        sa.Column("how_many", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column(
            "time",
            sa.Time(),
            server_default=sa.text("CURRENT_TIME"),
            nullable=False,
        ),
        sa.Column("replay_mode", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint(None, "task", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="unique")
    op.drop_table("replay")
    # ### end Alembic commands ###
