"""update task

Revision ID: 8f998c047924
Revises: 7d3c8748aaa2
Create Date: 2025-01-13 12:33:59.043448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f998c047924"
down_revision: Union[str, None] = "7d3c8748aaa2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "replay", ["id"])
    op.add_column("task", sa.Column("replay_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "task", ["replay_id"])
    op.create_foreign_key(None, "task", "replay", ["replay_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_constraint(None, "task", type_="unique")
    op.drop_column("task", "replay_id")
    op.drop_constraint(None, "replay", type_="unique")
    # ### end Alembic commands ###
